### ISSUE TITLE
missing field `platformInfoBlob`

### ISSUE THREAD

**Issue by lacabra** [enigmampc/discovery-docker-network#20]
**Describe the bug**
When booting up the network, right when the KM node tries to fetch the report from the Attestation Service, it errors out with the following
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `platformInfoBlob`", line: 1, column: 731)', src/libcore/result.rs:999:5
```

**To Reproduce**

Just launch the Docker network with `./launch.bash` but it seems to be system specific, because the very same network runs in other machines but not on this particular one.

**Desktop (please complete the following information):**
 - OS: Ubuntu 16.04
 - Kernel: Linux km 4.15.0-1041-azure #45-Ubuntu SMP Fri Mar 15 14:41:00 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- linux_sgx_driver: tried both versions `0.1` and `2.5`

**Backtrace**
```
km_1        | aesm_service[10]: [ADMIN]EPID Provisioning initiated
km_1        | aesm_service[10]: [ADMIN]EPID Provisioning successful
km_1        | Hardware mode, fetching report from the Attestation Service
km_1        | thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `platformInfoBlob`", line: 1, column: 731)', src/libcore/result.rs:999:5
km_1        | stack backtrace:
km_1        |    0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
km_1        |              at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
km_1        |    1: std::sys_common::backtrace::_print
km_1        |              at src/libstd/sys_common/backtrace.rs:71
km_1        |    2: std::panicking::default_hook::{{closure}}
km_1        |              at src/libstd/sys_common/backtrace.rs:59
km_1        |              at src/libstd/panicking.rs:197
km_1        |    3: std::panicking::default_hook
km_1        |              at src/libstd/panicking.rs:211
km_1        |    4: std::panicking::rust_panic_with_hook
km_1        |              at src/libstd/panicking.rs:474
km_1        |    5: std::panicking::continue_panic_fmt
km_1        |              at src/libstd/panicking.rs:381
km_1        |    6: rust_begin_unwind
km_1        |              at src/libstd/panicking.rs:308
km_1        |    7: core::panicking::panic_fmt
km_1        |              at src/libcore/panicking.rs:85
km_1        |    8: core::result::unwrap_failed
km_1        |              at /rustc/6afcb5628523b0baae5704ad34ac1aba8ba10de6/src/libcore/macros.rs:18
km_1        |    9: core::result::Result<T,E>::unwrap
km_1        |              at /rustc/6afcb5628523b0baae5704ad34ac1aba8ba10de6/src/libcore/result.rs:800
km_1        |   10: enigma_tools_u::attestation_service::service::AttestationService::unwrap_report_obj
km_1        |              at /root/enigma-core/enigma-tools-u/src/attestation_service/service.rs:157
km_1        |   11: enigma_tools_u::attestation_service::service::AttestationService::unwrap_result::{{closure}}
km_1        |              at /root/enigma-core/enigma-tools-u/src/attestation_service/service.rs:171
km_1        |   12: enigma_tools_u::attestation_service::service::AttestationService::unwrap_result
km_1        |              at /root/enigma-core/enigma-tools-u/src/attestation_service/service.rs:161
km_1        |   13: enigma_tools_u::attestation_service::service::AttestationService::unwrap_response
km_1        |              at /root/enigma-core/enigma-tools-u/src/attestation_service/service.rs:176
km_1        |   14: enigma_tools_u::attestation_service::service::AttestationService::send_request
km_1        |              at /root/enigma-core/enigma-tools-u/src/attestation_service/service.rs:124
km_1        |   15: enigma_tools_u::attestation_service::service::AttestationService::get_report::{{closure}}
km_1        |              at /root/enigma-core/enigma-tools-u/src/attestation_service/service.rs:97
km_1        |   16: enigma_tools_u::attestation_service::service::AttestationService::get_report
km_1        |              at /root/enigma-core/enigma-tools-u/src/attestation_service/service.rs:94
km_1        |   17: enigma_principal_app::boot_network::principal_manager::ReportManager::get_registration_params::{{closure}}
km_1        |              at src/boot_network/principal_manager.rs:94
km_1        |   18: enigma_principal_app::boot_network::principal_manager::ReportManager::get_registration_params
km_1        |              at src/boot_network/principal_manager.rs:76
km_1        |   19: <enigma_principal_app::boot_network::principal_manager::PrincipalManager as enigma_principal_app::boot_network::principal_manager::Sampler>::register::{{closure}}
km_1        |              at src/boot_network/principal_manager.rs:170
km_1        |   20: <enigma_principal_app::boot_network::principal_manager::PrincipalManager as enigma_principal_app::boot_network::principal_manager::Sampler>::register
km_1        |              at src/boot_network/principal_manager.rs:168
km_1        |   21: <enigma_principal_app::boot_network::principal_manager::PrincipalManager as enigma_principal_app::boot_network::principal_manager::Sampler>::verify_identity_or_register::{{closure}}
km_1        |              at src/boot_network/principal_manager.rs:197
km_1        |   22: <enigma_principal_app::boot_network::principal_manager::PrincipalManager as enigma_principal_app::boot_network::principal_manager::Sampler>::verify_identity_or_register
km_1        |              at src/boot_network/principal_manager.rs:188
km_1        |   23: <enigma_principal_app::boot_network::principal_manager::PrincipalManager as enigma_principal_app::boot_network::principal_manager::Sampler>::run::{{closure}}
km_1        |              at src/boot_network/principal_manager.rs:216
km_1        |   24: <enigma_principal_app::boot_network::principal_manager::PrincipalManager as enigma_principal_app::boot_network::principal_manager::Sampler>::run
km_1        |              at src/boot_network/principal_manager.rs:213
km_1        |   25: enigma_principal_app::cli::app::start::{{closure}}
km_1        |              at src/cli/app.rs:82
km_1        |   26: enigma_principal_app::cli::app::start
km_1        |              at src/cli/app.rs:14
km_1        |   27: enigma_principal_app::main
km_1        |              at src/main.rs:56
km_1        |   28: std::rt::lang_start::{{closure}}
km_1        |              at /rustc/6afcb5628523b0baae5704ad34ac1aba8ba10de6/src/libstd/rt.rs:64
km_1        |   29: std::panicking::try::do_call
km_1        |              at src/libstd/rt.rs:49
km_1        |              at src/libstd/panicking.rs:293
km_1        |   30: __rust_maybe_catch_panic
km_1        |              at src/libpanic_unwind/lib.rs:85
km_1        |   31: std::rt::lang_start_internal
km_1        |              at src/libstd/panicking.rs:272
km_1        |              at src/libstd/panic.rs:388
km_1        |              at src/libstd/rt.rs:48
km_1        |   32: std::rt::lang_start
km_1        |              at /rustc/6afcb5628523b0baae5704ad34ac1aba8ba10de6/src/libstd/rt.rs:64
km_1        |   33: main
km_1        |   34: __libc_start_main
km_1        |   35: _start
km_1        | root@km:~# aesm_service[103]: [ADMIN]White List update requested
km_1        | aesm_service[103]: [ADMIN]Platform Services initializing
km_1        | aesm_service[103]: [ADMIN]Platform Services initialization failed due to DAL error
km_1        | aesm_service[103]: [ADMIN]White list update request successful for Version: 52
km_1        | aesm_service[103]: The server sock is 0x560b2092e850
```

**Comment by lacabra** [comment]
Fixed in enigmampc/enigma-core#163
