### ISSUE TITLE
This isn't a delta

### ISSUE THREAD

**Issue by lacabra** [enigmampc/discovery-docker-network#25]
**Describe the bug**
When launching the network with more than 1 node, right at the very beginning, `core_1`throws with the following error:
```
core_1      | 16:28:27 [INFO] get_all_tips() => Err(ErrorMessage { msg: "This isn\'t a delta" }
```
I observe the same behavior with `NODES=2` and `NODES=3` but not with 1 node.
Cc: @AvishaiW 

**To Reproduce**

1. Using the following branches:
```
GIT_BRANCH_CORE=develop
GIT_BRANCH_P2P=victor
GIT_BRANCH_CONTRACT=develop
```
2. Launch the network with 2 nodes: `NODES=2 ./launch.bash`
3. Look at the network output for a stack trace

**Expected behavior**
This should not happen.

**Stack backtrace**
```
core_1      | 16:28:27 [INFO] get_all_tips() => Err(ErrorMessage { msg: "This isn\'t a delta" }
core_1      | 
core_1      | stack backtrace:
core_1      |    0: failure::backtrace::internal::InternalBacktrace::new::h8897179d1326eca2 (0x5557c2bb6993)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/internal.rs:44
core_1      |    1: failure::backtrace::Backtrace::new::h28ebfa57310292ca (0x5557c2bb673e)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/backtrace/mod.rs:111
core_1      |    2: <failure::error::error_impl::ErrorImpl as core::convert::From<F>>::from::h67ebc13f61c6c634 (0x5557c20c6c04)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/error_impl.rs:19
core_1      |    3: <failure::error::Error as core::convert::From<F>>::from::haa796ec67bad0797 (0x5557c20c5cfe)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error/mod.rs:36
core_1      |    4: failure::error_message::err_msg::hce056b237d21233c (0x5557c217a0d2)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/failure-0.1.5/src/error_message.rs:12
core_1      |    5: enigma_core_app::networking::messages::IpcDelta::from_delta_key::h6ea36525b9943d32 (0x5557c2167391)
core_1      |              at src/networking/messages.rs:202
core_1      |    6: enigma_core_app::networking::ipc_listener::handling::get_all_tips::{{closure}}::h78daab659d63776c (0x5557c2144815)
core_1      |              at src/networking/ipc_listener.rs:177
core_1      |    7: enigma_core_app::networking::ipc_listener::handling::get_all_tips::h25ba6f18374671ff (0x5557c20d9f6b)
core_1      |              at src/networking/ipc_listener.rs:172
core_1      |    8: enigma_core_app::networking::ipc_listener::handle_message::hb38ba647bcbb3e7e (0x5557c206c235)
core_1      |              at src/networking/ipc_listener.rs:40
core_1      |    9: enigma_core_app::main::{{closure}}::h5da1a85a6d0dd7fa (0x5557c20316b9)
core_1      |              at src/main.rs:35
core_1      |   10: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::h686e08f795c2d5d7 (0x5557c203156b)
core_1      |              at /rustc/6afcb5628523b0baae5704ad34ac1aba8ba10de6/src/libcore/ops/function.rs:279
core_1      |   11: core::option::Option<T>::map::h2b07fbef47d3f82b (0x5557c2032b7f)
core_1      |              at /rustc/6afcb5628523b0baae5704ad34ac1aba8ba10de6/src/libcore/option.rs:416
core_1      |   12: <futures::stream::map::Map<S,F> as futures::stream::Stream>::poll::he2de6cf866eb39e6 (0x5557c20324d1)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/stream/map.rs:79
core_1      |   13: <futures::stream::forward::Forward<T,U> as futures::future::Future>::poll::hbf09257d9bd4a1b7 (0x5557c20355eb)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/stream/forward.rs:94
core_1      |   14: <futures::future::map::Map<A,F> as futures::future::Future>::poll::hde322fa0abcf3721 (0x5557c2031b6e)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/map.rs:30
core_1      |   15: futures::future::chain::Chain<A,B,C>::poll::hd30877a90cdf390c (0x5557c2044c2c)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/chain.rs:32
core_1      |   16: <futures::future::and_then::AndThen<A,B,F> as futures::future::Future>::poll::h909658d3949cbd87 (0x5557c205690a)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/and_then.rs:32
core_1      |   17: futures::task_impl::Spawn<T>::poll_future_notify::{{closure}}::hfd6221d86729692b (0x5557c203b17a)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/mod.rs:329
core_1      |   18: futures::task_impl::Spawn<T>::enter::{{closure}}::hb67924a91fbc2b2a (0x5557c203b2f7)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/mod.rs:399
core_1      |   19: futures::task_impl::std::set::h2bcb805a30cf9058 (0x5557c2044431)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/std/mod.rs:83
core_1      |   20: futures::task_impl::Spawn<T>::enter::h662135498d395533 (0x5557c203b283)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/mod.rs:399
core_1      |   21: futures::task_impl::Spawn<T>::poll_fn_notify::hc0a745d0c8579819 (0x5557c203b0a5)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/mod.rs:291
core_1      |   22: futures::task_impl::Spawn<T>::poll_future_notify::hf438b3451b63c388 (0x5557c203b14e)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/mod.rs:329
core_1      |   23: futures::task_impl::std::<impl futures::task_impl::Spawn<F>>::wait_future::{{closure}}::h450f5f707858fe7f (0x5557c2044529)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/std/mod.rs:236
core_1      |   24: futures::task_impl::std::ThreadNotify::with_current::{{closure}}::h5ec25575cbfd6bbb (0x5557c204434f)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/std/mod.rs:483
core_1      |   25: std::thread::local::LocalKey<T>::try_with::h1a70fad5fcfa2bcb (0x5557c2049594)
core_1      |              at /rustc/6afcb5628523b0baae5704ad34ac1aba8ba10de6/src/libstd/thread/local.rs:299
core_1      |   26: std::thread::local::LocalKey<T>::with::h99b0651e577d580f (0x5557c2049391)
core_1      |              at /rustc/6afcb5628523b0baae5704ad34ac1aba8ba10de6/src/libstd/thread/local.rs:245
core_1      |   27: futures::task_impl::std::ThreadNotify::with_current::h8b9222ea60cf30ce (0x5557c204430e)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/std/mod.rs:483
core_1      |   28: futures::task_impl::std::<impl futures::task_impl::Spawn<F>>::wait_future::h70ca8fe0931bed09 (0x5557c203b324)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/task_impl/std/mod.rs:233
core_1      |   29: futures::future::Future::wait::hc753a5c6b67a2816 (0x5557c2056810)
core_1      |              at /root/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-0.1.27/src/future/mod.rs:299
core_1      |   30: enigma_core_app::main::hd29daed29fe49fb2 (0x5557c2034802)
core_1      |              at src/main.rs:34
core_1      |   31: std::rt::lang_start::{{closure}}::h576c409125acbaa4 (0x5557c2030110)
core_1      |              at /rustc/6afcb5628523b0baae5704ad34ac1aba8ba10de6/src/libstd/rt.rs:64
core_1      |   32: {{closure}} (0x5557c3012233)
core_1      |              at src/libstd/rt.rs:49
core_1      |       do_call<closure,i32>
core_1      |              at src/libstd/panicking.rs:293
core_1      |   33: __rust_maybe_catch_panic (0x5557c301668a)
core_1      |              at src/libpanic_unwind/lib.rs:85
core_1      |   34: try<i32,closure> (0x5557c3012dfd)
core_1      |              at src/libstd/panicking.rs:272
core_1      |       catch_unwind<closure,i32>
core_1      |              at src/libstd/panic.rs:388
core_1      |       lang_start_internal
core_1      |              at src/libstd/rt.rs:48
core_1      |   35: std::rt::lang_start::hd44344b157b8da3a (0x5557c20300e9)
core_1      |              at /rustc/6afcb5628523b0baae5704ad34ac1aba8ba10de6/src/libstd/rt.rs:64
core_1      |   36: main (0x5557c203499a)
core_1      |   37: __libc_start_main (0x7fdf7a515b97)
core_1      |   38: _start (0x5557c202eb2a)
core_1      |   39: <unknown> (0x0))
core_1      | 16:28:27 [ERROR] Unwrapped p2p Message failed: This isn't a delta
p2p_1       | (node:37) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'tips' of undefined
p2p_1       |     at onResponse (/root/enigma-p2p/src/worker/controller/actions/db/read/GetAllTipsAction.js:25:29)
p2p_1       |     at _controller.communicator.sendAndReceive.then (/root/enigma-p2p/src/worker/controller/actions/db/DbRequestAction.js:27:11)
p2p_1       | (node:37) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by AvishaiW** [comment]
@lacabra I updated all my repositories and updated all docker containers and I didn't experience this. Is it possible you are running on outdated code/image?

**Comment by lacabra** [comment]
I can't reproduce right now, either.
Closing it for now, will reopen if it ever appears again. 
Thank you.
